### ISSUE TITLE
The columns first_name and last_name are not culturally neutral in the person table

### ISSUE THREAD

**Issue by daverick** [jmbriano/tutorials#10]
It is not a good practice to use first_name and last_name as this is a western cultural traits (which even do not work for Spanish people who have 2 last name.
Explaining how to be culturally open is not the objective of this 1st SQL tutorial, but it should give bad habits.
first_name and last_name could be substitute by a simple column name and maybe have some diversity in the list

**Comment by jmbriano** [comment]
Ok to do this change. But a lot of refactor is needed. Specially section "Updating multiple records" in lesson 4. An alternative for this section could be to introduce the operator LIKE and use LIKE "%Moore%"

**Comment by brunogirin** [comment]
Agreed, we should change it. And yes we might as well introduce the `LIKE` operator in lesson 4, which is a good way to show updates on multiple records at the same time.

**Comment by daverick** [comment]
- refactoring is good!
- there is a list of the different subject to have in each lesson? 
- I always try to go one learning at a time. The like can be seen at the same time in then SELECT lessons. and used afterward unable multi update

**Comment by jmbriano** [comment]
(I never said refactoring was bad ;) )
Scope:
- Turn the two columns into a single "name" one. 
- Add some variety in the names (i.e Spanish with two last names)
- Refactor the subsequent lessons using the two columns.
- Add a section about LIKE in lesson 1. 
- Use LIKE in the multiple update in lesson 4

Effort: 2 hr.

**Comment by jmbriano** [comment]
I'm starting to fix this one

**Comment by jmbriano** [comment]
@daverick, @brunogirin, I've created PR #11 with the solution to this one. Let me know your thoughts.

It would be nice to merge this one before moving forward with the other fixes as they touch the same data (person table)

**Comment by jmbriano** [comment]
I've moved forward with the PR as there where no comments and I want to move forward with the other issues to PR to codebar before the end of the month
