### ISSUE TITLE
add link to solutions for the exercises in the SQL tutorial

### ISSUE THREAD

**Issue by daverick** [jmbriano/tutorials#4]
it shouldn't  be directly available in the same page but having them available is useful for learning.

**Comment by jmbriano** [comment]
Agree they are useful. Not sure what you meant in the description, but I think better in a separate page with a link from this one.

**Comment by brunogirin** [comment]
Could we have `.sql` files that the tutorial points to? That might be the simplest way to provide solutions. While we're at it, it might be good to provide some `.sql` files for setup too.

**Comment by daverick** [comment]
I updated my comment @jmbriano, now it should be understandable.

**Comment by jmbriano** [comment]
Scope:

- Export the Annexes into setup.sql
- Add one solutions.sql file per lesson and link it from the lesson page (follow the guidelines as discussed in #5)

Effort: ~1 hr (for someone that knows SQL already)

**Comment by jmbriano** [comment]
Blocked by the PR #13 which has changed the setup data and some exercises. Better to first merge that to avoid rework

**Comment by jmbriano** [comment]
Solutions had been provided by students trying out the tutorial. Issue can be closed
