### ISSUE TITLE
use SQL coding standard in the SQL tutorial from the start and the 1st tutorial

### ISSUE THREAD

**Issue by daverick** [jmbriano/tutorials#5]
good SQL coding habit should be shown and enforce from the start like:

- query on different lines with correct indentations
- use of plurals forms for the table names

**Comment by jmbriano** [comment]
:) good or bad depends a on the person. For example, all my studies I was thought to use singular names in the tables (and I still find a lot of articles online with this approach). This is very convenient when you do person.name for example (contrary to persons.name). 
Aligning SQL is yet another subjective topic. I wrote them different than Bruno (the other collaborator) and I'm sure you'd do different too.

Maybe the best is to define the tutorial style guide and follow it. While researching the topic I found: https://www.sqlstyle.guide/ Shall we make this our style @daverick?

**Comment by brunogirin** [comment]
Any consistent style is good and we can point to it in the tutorial so let's go for the one you found.

**Comment by daverick** [comment]
This one looks goods to me! and it use plural or collective nouns!

**Comment by jmbriano** [comment]
Scope:

- Add a section explaining the style guide (including the link) in lesson 1
- Re-write the lessons snippets of code following them.
- Rename the tables to plural forms
- Recreate all fiddles with the new table names.

Effort: ~2hr

**Comment by jmbriano** [comment]
I'm starting the implementation of this ticket

**Comment by jmbriano** [comment]
PR #14 created to fix this issue. @brunogirin @daverick please share your thoughts before I merge.

**Comment by jmbriano** [comment]
PR merged based on @brunogirin feedback. closing this issue. Thanks @brunogirin
