### ISSUE TITLE
the exercise 1.4 in the first SQL tutorial need something that is not in the tutorial

### ISSUE THREAD

**Issue by daverick** [jmbriano/tutorials#6]
you need to make a condition comparing 2 columns of the same table which has no precedence in th tutorial.
would be better to introduce an example in the tutorial.

**Comment by jmbriano** [comment]
Good catch 👍

**Comment by jmbriano** [comment]
Scope:
- Add an example of comparison of two columns in the first lesson.

Effort: 30 min

**Comment by jmbriano** [comment]
PR #12 ready for review and merge. I'll proceed with the merge by Sunday 28th if no comments are raised
