### ISSUE TITLE
in the exercise 1.5 in then first tutorial, the output of the solution contains null which has not be introduced

### ISSUE THREAD

**Issue by daverick** [jmbriano/tutorials#7]

**Comment by jmbriano** [comment]
Indeed, initially NULL was going to be in the first lesson but then we split it in two because it was already quite long. We could put a note in the 1.5 warning them that NULL will appear, and they will understand what that is in the next lesson. (Small hook to keep reading)

**Comment by brunogirin** [comment]
Yes, agreed, there might be a place to introduce `null` in earlier examples.

**Comment by daverick** [comment]
let's change the 1.5 with the different country of residences and deal with null in the second lesson?

**Comment by jmbriano** [comment]
Scope:
- Redefine the exercise to "different countries of residence"

Effort: 15 min
