### ISSUE TITLE
why introduce another table in the last exercise 1.7 of the 1st tutorial?

### ISSUE THREAD

**Issue by daverick** [jmbriano/tutorials#8]
it may lead to confusion for the student

**Comment by jmbriano** [comment]
The idea was that is not all about persons. I'm ok if you want to remove 1.7 and leave location table for future lessons. The fiddle and annexes should also be updated.

**Comment by jmbriano** [comment]
Scope:
- Remove the bullet 1.7
- Check if after doing so, there is still a need for location table in lesson 1. If not, remove it from the fiddle an from the annex.

Effort: 1hr
