### ISSUE TITLE
The column biological_sex in the person table is not inclusive 

### ISSUE THREAD

**Issue by daverick** [jmbriano/tutorials#9]
- This columns is really problematic on the inclusivity regarding gender, transgender ... It could even be felt as oppressive.
- This columns doesn't bring anything special and interesting for the learning experience. (if we really want have an example of binary (or trinary) values we can use left-handed, right-handed, ambidextre which should offend anyone)
It would be better to take it out and maybe in a later tutorial explain how to be open and inclusive to all gender option.
exercise 1.6 should be adapt if this change is made (why not ask for the studies of the people that have children?)

**Comment by jmbriano** [comment]
Here I'm a bit confused, I used biological_sex (in opposition to just sex) to avoid this problem of inclusion/oppression. Biological sex has to do with the genitalia of the person, and not with their identity. For this reason, I believe that the usage here is correct, and should not offend anyone. If you think it still may do, it can be changed to _Handedness_ as you suggest. Independently of the changes for the tutorial, lets discuss the next time we see each other about this.

**Comment by brunogirin** [comment]
I wasn't sure about that one, also bear in mind that sex is different from gender so it's more a problem for intersex people than transgender people, which the data currently deals with. That said, having that sort of data in a database is contentious to start with so for the purpose of this tutorial, it might be better to remove it altogether. Do we actually use it anywhere?

If you want to replace it with handedness, this might open up a whole lot of other complications as you need to consider ambidextrous and badly lateralised people (yes we exist!)

Generally speaking, I'd be partial to keeping the `person` table to the absolute minimum number of fields required and see if we can use any of the other tables for more complicated fields.

**Comment by brunogirin** [comment]
Another option: what about replacing the `biological_sex` column with a `pronouns` column? It would provide what we need for the tutorials without being controversial.

**Comment by daverick** [comment]
Yes it is something complicated and it is too easy to make mistake. We don’t need it for our learning process so we should avoid it. Maybe we can have a dedicated tutorial where we specifically talk about this subject with beforehand looking for expert in the subject and try to make a person table the more inclusive and correct possible!

**Comment by jmbriano** [comment]
Scope:

- Remove the biological sex column from the lessons, the annexes and the fiddles.
- Review its usage in the subsequent lessons. Refactor any example using it.

Effort: 1hr

**Comment by jmbriano** [comment]
PR #13 uploaded to solve this issue as agreed above. Comments are welcome so I can proceed with the merge.

**Comment by jmbriano** [comment]
@daverick @brunogirin Did you have the chance to review the PR #13 ?
I may have some time today to progress in the remaining issue, but better to merge this one first to reduce the merging issues.

**Comment by brunogirin** [comment]
@jmbriano sorry I didn't see the PR, it looks like my GitHub notifications are not very efficient at notifying me. I commented on it: I'm happy for it to be merged.
